function TableofSatellites = import_satellite_table(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  TABLEOFSATELLITES = IMPORTFILE(FILE) reads data from the first
%  worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the data as a table.
%
%  TABLEOFSATELLITES = IMPORTFILE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  TABLEOFSATELLITES = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  TableofSatellites = importfile("/Users/max/Desktop/icymoons_thermal_stress/underpressure/Table_of_Satellites.xlsx", "Sheet1", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 10-Jan-2025 10:38:21

%% Input handling

% If no sheet is specified, read from Sheet1
if nargin == 1 || isempty(sheetName)
    sheetName = "Sheet1";
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 8);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = dataLines(1, :);

% Specify column names and types
opts.VariableNames = ["Satellite", "DKm", "RcKm", "RcRp", "McMp", "MoI", "PcmbGpa", "PcGpa"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double", "double"];

% Specify variable properties
opts = setvaropts(opts, "Satellite", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Satellite", "EmptyFieldRule", "auto");

% Import the data
TableofSatellites = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = dataLines(idx, :);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    TableofSatellites = [TableofSatellites; tb]; %#ok<AGROW>
end

end